# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sdc-final-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://mcr.microsoft.com/
        username: ${{ secrets.AzureAppService_ContainerUsername_15086ced6f2f47f486658beb089c6e4b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_d830fe4041e44d7195a087f4e3d5b33e }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_15086ced6f2f47f486658beb089c6e4b }}/appsvc/staticsite:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sdc-final-project'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_f533111b573646d48f68bb3d65b9dc37 }}
        images: 'mcr.microsoft.com/${{ secrets.AzureAppService_ContainerUsername_15086ced6f2f47f486658beb089c6e4b }}/appsvc/staticsite:${{ github.sha }}'