# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sdc-final-project

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_570826e314cb41e09903ff2195b73c56 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_af8cafd123ed4f35a700b53dd2171011 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_570826e314cb41e09903ff2195b73c56 }}/mercury-dashboard-bartl:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sdc-final-project'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_956fcac83c0e43358175e96a828a494f }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_570826e314cb41e09903ff2195b73c56 }}/mercury-dashboard-bartl:${{ github.sha }}'